name: from_inventory_a
description:  A model that loads the complete service definition from the inventory
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2021 Inmanta
modulepath: libs
downloadpath: libs
repo:
    - git@github.com:inmanta/{}.git
install_mode: master
requires:
