name: LSM SR Linux Example
description: Provides and example of a LSM use case with SR Linux.
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
repo:
  - type: package
    url: https://packages.inmanta.com/public/quickstart/python/simple/
  - type: package
    url: https://packages.inmanta.com/<orchestrator-password>/inmanta-service-orchestrator-6-stable/python/simple/
  - type: package
    url: https://pypi.org/simple/
install_mode: release
requires:
