name: LSM SR Linux Example
description: Provides an example of a LSM use case with SR Linux.
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
install_mode: release
# This example requires licensed modules,
# replace <token> with inmanta access token you received with your license
pip:
  index_url: https://artifacts.internal.inmanta.com/inmanta/next
