name: LSM SR Linux Example
description: Provides an example of a LSM use case with SR Linux.
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
install_mode: release
# The repo block is for ISO6, inmanta-core<=10.0
repo:
  - type: package
    url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-6-stable/python/simple/
# The pip block is for ISO7 and up, inmanta-core>10.0
pip:
  index_url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-7-stable/python/simple/
