name: Cisco Examples
description: Provides examples for the Cisco module
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
repo:
    - https://github.com/inmanta/
install_mode: release
requires:
