version: '3'
services:
  postgres:
    container_name: inmanta_db
    image: postgres:13
    environment:
      POSTGRES_USER: inmanta
      POSTGRES_PASSWORD: inmanta
    networks:
      inm_net:
        ipv4_address: 172.30.0.2

  inmanta-server:
    container_name: inmanta_orchestrator
    image: ghcr.io/inmanta/orchestrator:2022
    ports:
      - 8888:8888
    networks:
      inm_net:
        ipv4_address: 172.30.0.3
    command: "server --wait-for-host inmanta_db --wait-for-port 5432"

networks:
  inm_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
