name: Cisco Examples
description: Provides examples for the Cisco module
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2021 Inmanta
modulepath: libs
downloadpath: libs
install_mode: release
# This example requires licensed modules,
# replace <token> with inmanta access token you received with your license
pip:
  index_url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-9-stable/python/simple/
