name: Cisco Examples
description: Provides examples for the Cisco module
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2021 Inmanta
modulepath: libs
downloadpath: libs
install_mode: release
# The repo block is for ISO6, inmanta-core<=10.0
# This example requires licensed modules, 
# replace <token> with inmanta access token you received with your license
repo:
  - type: package
    url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-6-stable/python/simple/
# The pip block is for ISO7 and up, inmanta-core>10.0
# This example requires licensed modules, 
# replace <token> with inmanta access token you received with your license
pip:
  index_url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-7-stable/python/simple/
