name: SR Linux Examples
description: Provides examples for the SR Linux module
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
install_mode: release
# The repo block is for ISO6
repo:
  - type: package
    url: https://packages.inmanta.com/public/quickstart/python/simple/
# The pip block is for ISO7 and up
pip:
  index_url: https://packages.inmanta.com/public/quickstart/python/simple/