name: SR Linux Examples
description: Provides examples for the SR Linux module
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
repo:
    - type: package
      url: https://packages.inmanta.com/public/quickstart/python/simple/
    - type: git
      url: https://github.com/inmanta/
install_mode: release
requires:
