name: lsm_updates
description:  A model that processes updates with cleanup
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2021 Inmanta
modulepath: libs
downloadpath: libs
repo:
  - type: package
    url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-6-stable/python/simple/
install_mode: master
requires:
