name: lsm_updates
description:  A model that processes updates with cleanup
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2021 Inmanta
modulepath: libs
downloadpath: libs
install_mode: master
requires:
# The repo block is for ISO6, inmanta-core<=10.0
repo:
  - type: package
    url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-6-stable/python/simple/
# The pip block is for ISO7 and up, inmanta-core>10.0
pip:
  index_url: https://packages.inmanta.com/<token>/inmanta-service-orchestrator-7-stable/python/simple/