#!/bin/bash
host_ip=$1
host_interface=$2
border_router_ip=$3

ip a show $host_interface
while [ $? -eq 1 ]
do
	sleep 1
        ip a show $host_interface
done

ip a add $host_ip dev $host_interface
ip route del default
ip route add default via $border_router_ip dev $host_interface
