name: de-allocation
description: 
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2021 Inmanta
modulepath: libs
downloadpath: libs
repo:
    - git@github.com:inmanta/{}.git
install_mode: release
requires:
